### ISSUE TITLE
Data is not being received in third party controller

### ISSUE THREAD

**Issue by I2000C** [bschwind/remote-cube#6]
Hi, I have connected my third party controller with the ESP32 correctly. However no data is being received by ESP32.
I have added a print of the number of <b>received bytes</b> and the <b>controller item</b> in the line 301 of _gamecube_controller.c_ to see the received data.
This is the output:
![image](https://user-images.githubusercontent.com/29607352/201921533-a9239cb2-c2ef-40e2-93fc-5314b733cddc.png)
If I press any button or stick, the output is the same...

Please, could you help me?

PS: The controller works perfectly on Wii without any adapters and on Wii U, Nintendo Switch and PC with the official Gamecube adapter.

**Comment by bschwind** [comment]
Hi @I2000C , is this involving any networking, or is it just about the controller connected directly to the ESP32, and the ESP32 doesn't read any data?

Since it's a third-party controller, it's possible the timing is different enough from a first-party controller that the code I've written doesn't quite handle it properly.

You'll have to dump the raw pulse data and see where things are going wrong, or hook up a digital logic analyzer to understand the pulses your controller is sending. I don't have a third party controller around so I can't test this easily, sorry.

**Comment by I2000C** [comment]
Hi, the problem is the communication between ESP32 and the controller.
I will try to analyze controller pulse data to fins what is wrong.
If I discover something, I will tell you.

**Comment by I2000C** [comment]
Hi again, I finally bought a Logic Analyzer in order to see what pulses were being received by the ESP32.
This is a capture of the program **PulseView**:

![image](https://user-images.githubusercontent.com/29607352/217019433-df8c6d05-829a-4382-871b-651beaa853f2.png)

As you can see, there aren't any pulses from the Gamecube controller :(

However, I connected the same controller to the official Gamecube adapter and then I connected the logic analyzer to the data pin.
![image](https://user-images.githubusercontent.com/29607352/217020012-456c9beb-482e-4d9d-9be0-0882239e7053.png)

Here, the Gamecube controller is receiving and sending the pulses correctly.

And if you put the first image next to the second:
![image](https://user-images.githubusercontent.com/29607352/217020640-bfc59b8d-5b3d-4ca8-80a5-b0ae2b081093.png)
you will notice that the selected area has the same pulses.
I believe these are the pulses sent from the ESP32 to the controller.

Besides, I have tested every wire and connections and all of them seem correct, so I think the problem must be a software parameter. The problem is that I don't know what could I change to get this working.

Do you have any ideas?

P.S.: I have attached the pulse files if you want to examine them (You will need to [download](https://sigrok.org/wiki/Downloads) the PulseView program to do that)
[pulses.zip](https://github.com/bschwind/remote-cube/files/10664956/pulses.zip)

**Comment by bschwind** [comment]
Hey @I2000C, thanks for getting back! It's been awhile since I've worked on this project so it'll take me a bit to look at this. In the meantime, please post any extra findings you have.

**Comment by I2000C** [comment]
Here I have attached an image showing the wire connections I have made. I hope it helps

![wire connections](https://user-images.githubusercontent.com/29607352/217385030-e539560c-e586-4da7-b80b-2c3f4b39dbcb.png)

Edited: My ESP32 model is: ESP32 WROOM-32

**Comment by I2000C** [comment]
I believe I have discovered what is going wrong.
When my ESP32 finish sending the command to the gamecube controller, the line is still active to 3.3V, so the controller cannot send its data.
Maybe this could be fixed if the line is disabled in the ESP32 after the command is sent to the controller.
However, the line shouldn't be fully disconnected. I think there should be some pull-up resistor or similar.

What do you think?

**Comment by I2000C** [comment]
Hi @bschwind, finally I got it working!

The main problem was that it was needed to enable the open drain mode.
I enabled it with this code (src: https://github.com/mongoose-os-libs/onewire-rmt/blob/master/src/onewire_rmt.c):
```c
       gpio_num_t pin = rx_config->input_pin;
       if (pin < 32) {
           GPIO.enable_w1ts = (0x1 << pin);
       } else {
           GPIO.enable1_w1ts.data = (0x1 << (pin - 32));
       }
       if (pin >= 0) {
           gpio_matrix_out(pin, SIG_GPIO_OUT_IDX, 0, 0);
       }
       
       // attach RMT channels to new gpio pin
       // ATTENTION: set pin for rx first since gpio_output_disable() will
       //            remove rmt output signal in matrix!
       rmt_set_pin(rmt_rx.channel, RMT_MODE_RX, pin);
       rmt_set_pin(rmt_tx.channel, RMT_MODE_TX, pin);
       // force pin direction to input to enable path to RX channel
       PIN_INPUT_ENABLE(GPIO_PIN_MUX_REG[pin]);
       
       GPIO.pin[pin].pad_driver = 1;
```

replacing these original code lines (lines 274 to 277 of gamecube_controller.c):

```c
    // Set the pin to both input and output mode, but not open drain.
    gpio_set_direction(rx_config->input_pin, GPIO_MODE_INPUT_OUTPUT);
    gpio_matrix_out(rx_config->input_pin, RMT_SIG_OUT0_IDX + tx_channel, 0, 0);
    gpio_matrix_in(rx_config->input_pin, RMT_SIG_IN0_IDX + rx_channel, 0);
```

Besides, I needed to add a 1KOhm resistor between the 3.3V and DATA pins.

After doing this, the ESP32 started receiving the controller data.

However, there was a problem when reading analog data (sticks and triggers).
The issue appeared to be the clock divider used in the rmt_rx config.
I changed it from 80 to 40 and that fixed the problem.

**Comment by bschwind** [comment]
Hi @I2000C , if you feel any of these changes should be in the main code, feel free to open a pull request! Sorry I wasn't much help but I'm happy to see you figured it out in the end!

**Comment by I2000C** [comment]
Ok, I will take that into account. However, I want to check if that solution works with an official controller before opening a pull request.

**Comment by I2000C** [comment]
Hi, I have tested the solution with another third party controller (different from the working one) and it doesn't work... :(
I will have to do some researching to find what is not working
